wkflw try 1.3

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -131,96 +131,96 @@ jobs:
               body: 'Website is published: [${{ steps.change-page-url.outputs.new_page_url }}](${{ steps.change-page-url.outputs.new_page_url }})'
             });
 
-  cleanup:
-    needs: deploy
-    permissions:
-      pages: write      
-      id-token: write
-      issues: write
-      pull-requests: write
+  # cleanup:
+  #   needs: deploy
+  #   permissions:
+  #     pages: write      
+  #     id-token: write
+  #     issues: write
+  #     pull-requests: write
 
-    runs-on: ubuntu-latest
-    steps:
-      - name: Get artifact ID from the latest successful run
-        id: get_artifact
-        uses: actions/github-script@v6
-        with:
-          script: |
-            const { owner, repo } = context.repo;
-            const workflow_id = 'github-actions.yml'; 
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Get artifact ID from the latest successful run
+  #       id: get_artifact
+  #       uses: actions/github-script@v6
+  #       with:
+  #         script: |
+  #           const { owner, repo } = context.repo;
+  #           const workflow_id = 'github-actions.yml'; 
 
-            console.log('Récupération des derniers artefacts');
-            const runs = await github.rest.actions.listWorkflowRuns({
-              owner,
-              repo,
-              workflow_id: workflow_id,
-              status: "success",
-              per_page: 1
-            });
+  #           console.log('Récupération des derniers artefacts');
+  #           const runs = await github.rest.actions.listWorkflowRuns({
+  #             owner,
+  #             repo,
+  #             workflow_id: workflow_id,
+  #             status: "success",
+  #             per_page: 1
+  #           });
 
-            if (runs.data.total_count === 0) { 
-              console.log("Aucun artefact trouvé. On continue quand même.");
-              return;
-            }
+  #           if (runs.data.total_count === 0) { 
+  #             console.log("Aucun artefact trouvé. On continue quand même.");
+  #             return;
+  #           }
 
-            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
-              owner,
-              repo,
-              run_id: runs.data.workflow_runs[0].id
-            });
+  #           const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
+  #             owner,
+  #             repo,
+  #             run_id: runs.data.workflow_runs[0].id
+  #           });
 
-            const artifact = artifacts.data.artifacts.find(a => a.name === "github-pages");
-            if (artifact) {
-              console.log("Artifact trouvé avec ID :", artifact.id);
-              const response = await github.rest.actions.downloadArtifact({
-                owner,
-                repo,
-                artifact_id: artifact.id,
-                archive_format: 'zip'
-              });
-              require('fs').writeFileSync("github-pages.zip", Buffer.from(response.data));
-              require('child_process').execSync(`unzip -o github-pages.zip -d "/tmp/gh-artifact-extract" && mkdir -p docs/site && tar xvf /tmp/gh-artifact-extract/artifact.tar -C docs/site/`);
-              console.log("Artefact téléchargé et extrait");
-            } else {
-              console.log("Aucun artefact trouvé.");
-            }
+  #           const artifact = artifacts.data.artifacts.find(a => a.name === "github-pages");
+  #           if (artifact) {
+  #             console.log("Artifact trouvé avec ID :", artifact.id);
+  #             const response = await github.rest.actions.downloadArtifact({
+  #               owner,
+  #               repo,
+  #               artifact_id: artifact.id,
+  #               archive_format: 'zip'
+  #             });
+  #             require('fs').writeFileSync("github-pages.zip", Buffer.from(response.data));
+  #             require('child_process').execSync(`unzip -o github-pages.zip -d "/tmp/gh-artifact-extract" && mkdir -p docs/site && tar xvf /tmp/gh-artifact-extract/artifact.tar -C docs/site/`);
+  #             console.log("Artefact téléchargé et extrait");
+  #           } else {
+  #             console.log("Aucun artefact trouvé.");
+  #           }
 
-      - name: Supprimer le dossier associé à la PR fermée
-        run: |
-          branch_name="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
-          echo "branch_name: $branch_name"
+  #     - name: Supprimer le dossier associé à la PR fermée
+  #       run: |
+  #         branch_name="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
+  #         echo "branch_name: $branch_name"
 
-          echo "📂 Contenu extrait de artifact.tar :"
-          ls -R docs/site/
+  #         echo "📂 Contenu extrait de artifact.tar :"
+  #         ls -l docs/site/
 
-          folder_path="docs/site/${branch_name}"
-          echo "folder_path: $folder_path"
+  #         folder_path="docs/site/${branch_name}"
+  #         echo "folder_path: $folder_path"
 
-          if [ -z "$folder_path" ]; then
-            echo "❌ Aucun dossier trouvé pour la branche ${branch_name} !"
-            exit 1
-          else
-            echo "🛠️ Chemin réel du dossier à supprimer : $folder_path"
-            rm -rf "$folder_path"
-            echo "✅ Dossier supprimé avec succès."
-          fi
+  #         if [ -z "$folder_path" ]; then
+  #           echo "❌ Aucun dossier trouvé pour la branche ${branch_name} !"
+  #           exit 1
+  #         else
+  #           echo "🛠️ Chemin réel du dossier à supprimer : $folder_path"
+  #           rm -rf "$folder_path"
+  #           echo "✅ Dossier supprimé avec succès."
+  #         fi
 
-          ls -R docs/site/
+  #         ls -l docs/site/
 
-      - name: Upload static files as artifact
-        id: deployment
-        uses: actions/upload-pages-artifact@v3
-        with:
-          path: docs/site
+  #     - name: Upload static files as artifact
+  #       id: deployment
+  #       uses: actions/upload-pages-artifact@v3
+  #       with:
+  #         path: docs/site
 
-      - name: Post cleanup comment
-        run: |
-          echo "Commentaire après nettoyage"
-          github.rest.issues.createComment({
-            issue_number: context.payload.pull_request.number,
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            body: 'Cleanup completed for PR and associated branch: [${{ github.event.pull_request.head.ref }}]'
-          });
+  #     - name: Post cleanup comment
+  #       run: |
+  #         echo "Commentaire après nettoyage"
+  #         github.rest.issues.createComment({
+  #           issue_number: context.payload.pull_request.number,
+  #           owner: context.repo.owner,
+  #           repo: context.repo.repo,
+  #           body: 'Cleanup completed for PR and associated branch: [${{ github.event.pull_request.head.ref }}]'
+  #         });
 
 
